{"name": "test_getbyid_failure", "status": "passed", "start": 1729276792666, "stop": 1729276792666, "uuid": "6f1b19c7-0179-4879-8676-4d2ec5fa43eb", "historyId": "cbc29a25fe64c1c9081b3685cd78d352", "testCaseId": "cbc29a25fe64c1c9081b3685cd78d352", "fullName": "Exercise.exercise_test.TestExerciseServiceWithoutMock#test_getbyid_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithoutMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}