{"name": "test_getbyid_failure", "status": "passed", "start": 1729285899532, "stop": 1729285899532, "uuid": "179af7c1-7271-4044-81ef-fac74ee7d308", "historyId": "cbc29a25fe64c1c9081b3685cd78d352", "testCaseId": "cbc29a25fe64c1c9081b3685cd78d352", "fullName": "Exercise.exercise_test.TestExerciseServiceWithoutMock#test_getbyid_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithoutMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "3648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}