{"name": "test_getbyname_failure", "status": "passed", "start": 1729323391898, "stop": 1729323391898, "uuid": "8a0bc49e-f22c-47a5-8436-57a8fc15c332", "historyId": "a93088beb91554d7a6f791d56bf46900", "testCaseId": "a93088beb91554d7a6f791d56bf46900", "fullName": "Exercise.exercise_test.TestExerciseServiceWithoutMock#test_getbyname_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithoutMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "16652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}