{"name": "test_getbyname_failure", "status": "passed", "start": 1729276792659, "stop": 1729276792660, "uuid": "310dc658-7704-4ab2-98e4-40c13f248dac", "historyId": "da79b9892db5ab531f3b11a7f1273cec", "testCaseId": "da79b9892db5ab531f3b11a7f1273cec", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyname_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}