{"name": "test_getbyname_failure", "status": "passed", "start": 1729284976046, "stop": 1729284976047, "uuid": "20792164-86c0-4338-a25b-68689948d971", "historyId": "da79b9892db5ab531f3b11a7f1273cec", "testCaseId": "da79b9892db5ab531f3b11a7f1273cec", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyname_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "12956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}