{"name": "test_getbyid_failure", "status": "passed", "start": 1729284976041, "stop": 1729284976042, "uuid": "c5cdc990-cb0f-4c73-a555-49042760bb78", "historyId": "440d2917e2e3c9db6ce38bcef72ba8ca", "testCaseId": "440d2917e2e3c9db6ce38bcef72ba8ca", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyid_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "12956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}