{"name": "test_getbyid_failure", "status": "passed", "start": 1729323391915, "stop": 1729323391915, "uuid": "f4ad9b7c-c798-4622-8635-03d8808bc136", "historyId": "440d2917e2e3c9db6ce38bcef72ba8ca", "testCaseId": "440d2917e2e3c9db6ce38bcef72ba8ca", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyid_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "9712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}