{"name": "test_getbyname_failure", "status": "passed", "start": 1729323995252, "stop": 1729323995252, "uuid": "13cf4d0a-ed26-41e8-bf64-0baf1c46fd4f", "historyId": "a93088beb91554d7a6f791d56bf46900", "testCaseId": "a93088beb91554d7a6f791d56bf46900", "fullName": "Exercise.exercise_test.TestExerciseServiceWithoutMock#test_getbyname_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithoutMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "19768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}