{"name": "test_getbyid_failure", "status": "passed", "start": 1729324713477, "stop": 1729324713485, "uuid": "a81fc615-74e4-4f01-9083-fe3f74b98d27", "historyId": "440d2917e2e3c9db6ce38bcef72ba8ca", "testCaseId": "440d2917e2e3c9db6ce38bcef72ba8ca", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyid_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "2016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}