{"name": "test_getbyname_failure", "status": "passed", "start": 1729276821984, "stop": 1729276821985, "uuid": "3e2bf642-2f49-4ebb-a8ed-5ec8269e76bf", "historyId": "a93088beb91554d7a6f791d56bf46900", "testCaseId": "a93088beb91554d7a6f791d56bf46900", "fullName": "Exercise.exercise_test.TestExerciseServiceWithoutMock#test_getbyname_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithoutMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "8848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}