{"name": "test_getbyname_failure", "status": "passed", "start": 1729079583579, "stop": 1729079583579, "uuid": "6052421f-0ad4-4408-99b5-662c5161f360", "historyId": "da79b9892db5ab531f3b11a7f1273cec", "testCaseId": "da79b9892db5ab531f3b11a7f1273cec", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyname_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "1956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}