{"name": "test_getbyid_failure", "status": "passed", "start": 1729274488675, "stop": 1729274488675, "uuid": "59a094a1-399f-4db9-be52-6b6b436bf8bc", "historyId": "440d2917e2e3c9db6ce38bcef72ba8ca", "testCaseId": "440d2917e2e3c9db6ce38bcef72ba8ca", "fullName": "Exercise.exercise_test.TestExerciseServiceWithMock#test_getbyid_failure", "labels": [{"name": "parentSuite", "value": "Exercise"}, {"name": "suite", "value": "exercise_test"}, {"name": "subSuite", "value": "TestExerciseServiceWithMock"}, {"name": "host", "value": "DESKTOP-IDGJ8R7"}, {"name": "thread", "value": "7844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Exercise.exercise_test"}]}